paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la BD
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno en el servidor
        "401":
          description: El usuario no inició sesión
    post:
      summary: Registra un nuevo producto en la base de datos
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/productData"
      responses:
        "201":
          description: El nuevo producto se registró con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno en el servidor
        "401":
          description: El usuario no inició sesión
  /api/products/{pid}:
    get:
      summary: Obtiene el producto a partir del ID pasado por parámetro.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que desea buscar.
          schema:
            $type: String
      responses:
        "200":
          description: El producto se obtuvo satisfactoriamente de la base de datos!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno en el servidor
        "401":
          description: El usuario no inició sesión
    put:
      summary: Modificar un producto a partir del ID pasado por parámetro.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que desea modificar.
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/productData"
      responses:
        "200":
          description: El producto se modificó con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno en el servidor
        "401":
          description: El usuario no inició sesión
    delete:
      summary: Borrar un producto de la base de datos, a partir del ID pasado por parámetro.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que desea borrar.
          schema:
            $type: String
      responses:
        "200":
          description: El producto se borró con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno en el servidor
        "401":
          description: El usuario no inició sesión
components:
  schemas:
    Producto:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerada por MongoDB
        title:
          type: String
          description: Título del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Stock del producto
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: String
          description: Imágenes del producto
        owner:
          type: String
          description: Creador del producto
      example:
        _id: ObjectId("65f3156d9c2d9cff1a3d7f73")
        title: Computador portatil HP 15 Pulgadas Ef2524la
        description: Procesador AMD R5 Ram 8GB DiscoSSD 512 GB
        price: 1280
        code: 223478
        stock: 90
        category: computadores
        thumbnail: https://fullhogar.com.co/wp-content/uploads/2023/05/WA13T5260BYGRIS-2.jpg
        owner: kevin@gmail.com
    Carrito:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerada por MongoDB
        products:
          type: Array
          description: Productos agregados al carrito
          $ref: "#/components/schemas/Producto"
      example:
        _id: ObjectId("65f31d51d4da1294285f54ba")
        products: [{ "product": "65f3156d9c2d9cff1a3d7f73", "quantity": 44 }]
  requestBodies:
    productData:
      type: object
      properties:
        title:
          type: String
          description: Título del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Stock del producto
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: String
          description: Imágenes del producto
      example:
        title: Computador portatil HP 15 Pulgadas Ef2524la
        description: Procesador AMD R5 Ram 8GB DiscoSSD 512 GB
        price: 1280
        code: 223478
        stock: 90
        category: computadores
        thumbnail: https://fullhogar.com.co/wp-content/uploads/2023/05/WA13T5260BYGRIS-2.jpg
